

services:
  # MySQL 데이터베이스
  mysql:
    image: mysql:8.0
    container_name: cinema_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cinema_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI 백엔드
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cinema_backend
    restart: always
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PORT: 3306
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - cinema_network
    volumes:
      - ./backend:/app

  # Nginx 프론트엔드
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: cinema_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - cinema_network
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./assets:/usr/share/nginx/html/assets:ro
      - ./js:/usr/share/nginx/html/js:ro
      - ./css:/usr/share/nginx/html/css:ro

networks:
  cinema_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local